"""Constants for the app"""

import logging

LOGGER: logging.Logger = logging.getLogger(__name__)


# The new voices are currently not listed in the Voice List API or documentation.
# Will retrieve voice list from tts.speech.microsoft.com/cognitiveservices/voices/list in the future
# TODO: Split voices by language
AZURE_HD_VOICES = {
    # "de-DE-Seraphina": "de-DE-Seraphina:DragonHDLatestNeural",
    # "en-US-Andrew": "en-US-Andrew:DragonHDLatestNeural",
    "Andrew": "en-US-Andrew2:DragonHDLatestNeural",
    "Aria": "en-US-Aria:DragonHDLatestNeural",
    "Ava": "en-US-Ava:DragonHDLatestNeural",
    "Brian": "en-US-Brian:DragonHDLatestNeural",
    "Davis": "en-US-Davis:DragonHDLatestNeural",
    # "Emma": "en-US-Emma:DragonHDLatestNeural",
    "Emma": "en-US-Emma2:DragonHDLatestNeural",
    "Jenny": "en-US-Jenny:DragonHDLatestNeural",
    "Steffan": "en-US-Steffan:DragonHDLatestNeural",
    # "ja-JP-Masaru": "ja-JP-Masaru:DragonHDLatestNeural",
    # "zh-CN-Xiaochen": "zh-CN-Xiaochen:DragonHDLatestNeural",
}


SUPPORTED_LANGUAGES = {
    "af-ZA": "Afrikaans (South Africa)",
    "sq-AL": "Albanian (Albania)",
    "am-ET": "Amharic (Ethiopia)",
    "ar-EG": "Arabic (Egypt)",
    "ar-SA": "Arabic (Saudi Arabia)",
    "hy-AM": "Armenian (Armenia)",
    "az-AZ": "Azerbaijani (Azerbaijan)",
    "eu-ES": "Basque (Basque)",
    "bn-IN": "Bengali (India)",
    "bs-BA": "Bosnian (Bosnia and Herzegovina)",
    "bg-BG": "Bulgarian (Bulgaria)",
    "my-MM": "Burmese (Myanmar)",
    "ca-ES": "Catalan (Spain)",
    "zh-HK": "Chinese (Cantonese, Traditional)",
    "zh-CN": "Chinese (Mandarin, Simplified)",
    "zh-TW": "Chinese (Taiwanese Mandarin)",
    "hr-HR": "Croatian (Croatia)",
    "cs-CZ": "Czech (Czech)",
    "da-DK": "Danish (Denmark)",
    "nl-BE": "Dutch (Belgium)",
    "nl-NL": "Dutch (Netherlands)",
    "en-AU": "English (Australia)",
    "en-CA": "English (Canada)",
    "en-HK": "English (Hong Kong SAR)",
    "en-IN": "English (India)",
    "en-IE": "English (Ireland)",
    "en-GB": "English (United Kingdom)",
    "en-US": "English (United States)",
    "et-EE": "Estonian (Estonia)",
    "fil-PH": "Filipino (Philippines)",
    "fi-FI": "Finnish (Finland)",
    "fr-BE": "French (Belgium)",
    "fr-CA": "French (Canada)",
    "fr-FR": "French (France)",
    "fr-CH": "French (Switzerland)",
    "gl-ES": "Galician (Galician)",
    "ka-GE": "Georgian (Georgia)",
    "de-AT": "German (Austria)",
    "de-DE": "German (Germany)",
    "de-CH": "German (Switzerland)",
    "el-GR": "Greek (Greece)",
    "he-IL": "Hebrew (Israel)",
    "hi-IN": "Hindi (India)",
    "hu-HU": "Hungarian (Hungary)",
    "is-IS": "Icelandic (Iceland)",
    "id-ID": "Indonesian (Indonesia)",
    "ga-IE": "Irish (Ireland)",
    "it-IT": "Italian (Italy)",
    "ja-JP": "Japanese (Japan)",
    "jv-ID": "Javanese (Indonesia)",
    "kn-IN": "Kannada (India)",
    "kk-KZ": "Kazakh (Kazakhstan)",
    "km-KH": "Khmer (Cambodia)",
    "ko-KR": "Korean (Korea)",
    "lo-LA": "Lao (Laos)",
    "lv-LV": "Latvian (Latvia)",
    "lt-LT": "Lithuanian (Lithuania)",
    "mk-MK": "Macedonian (North Macedonia)",
    "ms-MY": "Malay (Malaysia)",
    "ml-IN": "Malayalam (India)",
    "mt-MT": "Maltese (Malta)",
    "mn-MN": "Mongolian (Mongolia)",
    "ne-NP": "Nepali (Nepal)",
    "nb-NO": "Norwegian (Bokmål, Norway)",
    "ps-AF": "Pashto (Afghanistan)",
    "fa-IR": "Persian (Iran)",
    "pl-PL": "Polish (Poland)",
    "pt-BR": "Portuguese (Brazil)",
    "pt-PT": "Portuguese (Portugal)",
    "ro-RO": "Romanian (Romania)",
    "ru-RU": "Russian (Russia)",
    "sr-RS": "Serbian (Cyrillic, Serbia)",
    "si-LK": "Sinhala (Sri Lanka)",
    "sk-SK": "Slovak (Slovakia)",
    "sl-SI": "Slovenian (Slovenia)",
    "so-SO": "Somali (Somalia)",
    "es-MX": "Spanish (Mexico)",
    "es-ES": "Spanish (Spain)",
    "su-ID": "Sundanese (Indonesia)",
    "sw-KE": "Swahili (Kenya)",
    "sv-SE": "Swedish (Sweden)",
    "ta-IN": "Tamil (India)",
    "te-IN": "Telugu (India)",
    "th-TH": "Thai (Thailand)",
    "tr-TR": "Turkish (Türkiye)",
    "uk-UA": "Ukrainian (Ukraine)",
    "ur-PK": "Urdu (Pakistan)",
    "uz-UZ": "Uzbek (Uzbekistan)",
    "vi-VN": "Vietnamese (Vietnam)",
    "cy-GB": "Welsh (United Kingdom)",
    "zu-ZA": "Zulu (South Africa)",
}
